# Environment file generation
# This file generates the .env file used by Docker Compose
# It aggregates configuration values from various Terraform resources

locals {
  env_config = {
    DOMAIN = {
      description = "Domain name for Traefik routing (e.g., api.platform.${desec_domain.domain.name})"
      value       = "${desec_rrset.rrset-a.subname}.${desec_domain.domain.name}"
    }
  }
}

resource "local_file" "env_file" {
  content = <<-EOF
# Environment configuration for Docker Compose
# This file is automatically generated by Terraform
# Do not edit manually - changes will be overwritten

${join("\n", [
  for key, config in local.env_config : <<-VAR
# ${config.description}
${key}=${config.value}
VAR
])}
EOF

filename        = "${path.module}/.env"
file_permission = "0644"
}
